service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  profile: incessantmeraki
  region: ap-southeast-2
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
